// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinAIBar.Core.Data;

#nullable disable

namespace WinAIBar.Core.Data.Migrations
{
    [DbContext(typeof(WinAIBarDbContext))]
    [Migration("20260523101214_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("WinAIBar.Core.Data.Entities.QuotaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("Limit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ResetsAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Used")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Utilization")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("Quotas");
                });

            modelBuilder.Entity("WinAIBar.Core.Data.Entities.SnapshotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CapturedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawPayload")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "CapturedAt")
                        .IsDescending(false, true);

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("WinAIBar.Core.Data.Entities.QuotaEntity", b =>
                {
                    b.HasOne("WinAIBar.Core.Data.Entities.SnapshotEntity", null)
                        .WithMany("Quotas")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WinAIBar.Core.Data.Entities.SnapshotEntity", b =>
                {
                    b.Navigation("Quotas");
                });
#pragma warning restore 612, 618
        }
    }
}
